### ISSUE TITLE
Smarter Emoji Lookup

### ISSUE THREAD

**Issue by nchase** [twinlabs/forum#100]
emoji functionality currently works, but it would be more correct if it was a mapping between a colon-delimited keyword and an arbitrary image URL (relative path, preferably).

we can accomplish this by:
1. [ ] adding an `emoji` table to the database where we do this mapping. the table will have three fields:
   1. keyword (string)
   2. url (string)
   3. classname (string w/ some default value) - this piece will give us the flexibility to style different sets of emoji differently.
2. [ ] add some glue code that knows how to do the database lookup, given a particular colon-delimited keyword.
3. [ ] implement an in-memory cache, e.g. `redis` via [`node_redis`](https://github.com/mranney/node_redis), for the new DB table so that we don't have to do a DB lookup every time someone needs to see an emoji.  
   
   if you haven't seen `redis`, it's like memcached but better. the in-memory cache will need to be generated when the server is started up.

Emoji to add (folded in from #121):
- [ ] "American Flag Never Forget Salute Guy" emoji (can anyone track this down?)

**Comment by nchase** [comment]
https://github.com/bevacqua/horsey is one potential timesaver. Twitter had a project too but it is relatively un-maintained (though assumed to be stable)

**Comment by OlaRossum** [comment]
Here is some other reactions:

![1f44d](https://user-images.githubusercontent.com/33274196/32355337-6449f930-c02e-11e7-828b-7ad41846f40c.png)
![1f44e](https://user-images.githubusercontent.com/33274196/32355339-64def076-c02e-11e7-8bbf-e4be8ac6320f.png)
![1f60d](https://user-images.githubusercontent.com/33274196/32355340-64fc03b4-c02e-11e7-88f2-b911a950e460.png)
![1f62d](https://user-images.githubusercontent.com/33274196/32355341-65786a4e-c02e-11e7-9238-142c4228d2e0.png)
![1f62f](https://user-images.githubusercontent.com/33274196/32355342-65dadcce-c02e-11e7-80b9-642d586c766c.png)
![1f602](https://user-images.githubusercontent.com/33274196/32355343-669120c4-c02e-11e7-9e75-e8075012d317.png)
![1f611](https://user-images.githubusercontent.com/33274196/32355344-66add822-c02e-11e7-87f7-4f430cee245b.png)
![1f621](https://user-images.githubusercontent.com/33274196/32355345-672e66a4-c02e-11e7-9364-1e0b9700fbdc.png)
![1f641](https://user-images.githubusercontent.com/33274196/32355346-67501e48-c02e-11e7-96e5-def3cecd8949.png)
![1f642](https://user-images.githubusercontent.com/33274196/32355347-677296da-c02e-11e7-9ae4-322a8c74a767.png)

**Comment by nchase** [comment]
Thanks @OlaRossum for touching this! It has been a while.

My current thinking on the topic is that all we'll need to do is maintain a small list of things that fall outside of the reach of the emoji standard. For different forums these may be different lists of group-relevant things. (e.g. for my friend group's forum, we want to use keywords that map to graphics that were available on our old forum)

That being said, the basic outline of this still applies (i.e. have a store of these things and in posts, generate these things for viewers if the content of the post says that we should have one).
