### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by jasonbekolay** [twinlabs/forum#117]
I've been working on creating an API for the forum.  Have a look at the restApi branch.  I still need to add a check for authentication, and ensure that you can't delete/edit the posts of others.

I've been considering creating an alternate frontend that I can use to post from work, an API would be useful for that.  Would be useful for other things too.  Comments?

**Comment by nchase** [comment]
this is a great idea. I was looking at the branch earlier today but didn't see this issue until now.

I'm very much into it. Looking forward to seeing the pull request when it's ready.
