### ISSUE TITLE
Posts won't post

### ISSUE THREAD

**Issue by ty2k** [twinlabs/forum#120]
Can't post via mobile or web across all browsers in either compact or expanded mode right now. The browser reports no errors when I try to post, but no new posts get added. Any way I can log an attempt in FireFox or Chrome to help debug this?

**Comment by nchase** [comment]
@ty2k: can't reproduce here.

in chrome, if you open your Developer Tools, are there any errors reported  in the console there?

**Comment by ty2k** [comment]
`http://asrv-a.akamaihd.net/sd/1017/1008.js Failed to load resource: the server responded with a status of 400 (Bad Request)`

**Comment by ty2k** [comment]
```http://asrv-a.akamaihd.net/sd/1017/1008.js Failed to load resource: the server responded with a status of 400 (Bad Request)
socket.io.js:2371 WebSocket connection to 'ws://f.orum.co/socket.io/1/websocket/1sVMCqnN3CmZf1oRVifz' failed: Error during WebSocket handshake: Unexpected response code: 200```

**Comment by nchase** [comment]
that first failure is pecular. we don't serve anything from akamai. makes me wonder who is providing the internet you're on and if they're handling network traffic in some weird way (e.g. changing headers around, adding content).

this dovetails nicely with the response from the second one (`200`) – response for that websocket request should be a `101`, and our server would never respond with a `200`. a `200` would be possible if someone (e.g. the internet provider where you are) was intercepting the request, figuring out what to do with it and sending back  some request of their own that they decided was appropriate.

**Comment by nchase** [comment]
ps: really appreciate you posting the error message.
