### ISSUE TITLE
Persist 'Last Visited' to DB

### ISSUE THREAD

**Issue by nchase** [twinlabs/forum#126]
Currently the 'last visited' info lives on the client side in `localStorage`. This isn't bad, but it's less than ideal if you're using multiple devices. These days, everyone is using multiple devices.

As @jasonbekolay points out, if done correctly, this will pave the way for Smarter Post/Thread 'Pagination' (#125)

**Comment by jasonbekolay** [comment]
:+1: 

Some though might be required around the websocket - when a new reply is pushed to the user over the socket, do you we update the last visited time as well?

**Comment by nchase** [comment]
hmm...good question. that seems like the _right_ thing to do as much as I kinda don't want to do it.

**Comment by jasonbekolay** [comment]
Not necessarily.  If I leave a tab open in the background, I'd rather not have any new posts marked as read.  I'd really only want that if the tab was in focus and that post was viewable on the page.  Something like that would be a fair bit more work, as the client would have to tell the server what's read as they scroll.  So maybe as a starting point, don't worry about it.

**Comment by nchase** [comment]
:thumbsup:

**Comment by nchase** [comment]
wouldn't have considered the "tab is open in the background" scenario until after the damage was done :thumbsup: :thumbsup: :zap: :mortar_board:
