### ISSUE TITLE
start using ES6

### ISSUE THREAD

**Issue by nchase** [twinlabs/forum#145]
6-to-5 (if necessary), io.js, etc.

**Comment by jasonbekolay** [comment]
backend or frontend?

In the case of the frontend, if you do the ember rewrite, you get ES6 for free.  Ember CLI has babel built in to its build process.

**Comment by nchase** [comment]
@jasonbekolay: both! glad to hear that ember has built-in ES6 transpiling. sounds great.

the thing that really pushed me over the line for this was actually a backend issue though. since we have a few SQL queries that are written by hand, it's really convenient to have stuff like multi-line strings and string interpolation. [ES6 finally has those](http://updates.html5rocks.com/2015/01/ES6-Template-Strings). 

the ES5-and-earlier alternatives are very difficult to maintain and/or difficult to read.

**Comment by nchase** [comment]
> Ember CLI has **babel** built in to its build process.

oh cool, looks like '6-to-5' and 'babel' are the same thing :thumbsup:
