### ISSUE TITLE
Textbox selection/editing on mobile device is inaccurate

### ISSUE THREAD

**Issue by useffc** [twinlabs/forum#172]
On mobile Safari (iOS 9.1), selecting text in a ```textbox``` element is inaccurate. This bug impacts post editing and can be very confusing.

Steps to reproduce: 
1) Edit a post
2) Select after the last character in the post
3) Move the cursor one character to the left of the selection
4) Backspace/delete

The outcome should be that the penultimate character is deleted, but instead an earlier character than that is deleted.

This is almost certainly a product of ```font-family``` for post creating/editing being set to ```Avenir```. Changing font families resolves the issue.

**Comment by nchase** [comment]
fixed so closing issue.
